config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'projects#index'
  resources :tasks do
    member do
      patch :complete
    end
  end
  resources :projects
  get 'next_seven_days' =>'tasks#next_seven_days'
  get 'today' =>'tasks#today'
  get 'projects/:project_id/search' => 'tasks#search', as: :search
  get 'completed' => 'tasks#completed', as: :completed_tasks
  get 'cancel_task_form' => 'tasks#cancel'
  get 'cancel_project_form' => 'projects#cancel'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  enum priority: {red: 3, yellow: 2, white: 1}

  def deadline_format
    deadline.strftime("%d %b") unless deadline.nil?
  end

  def deadline_format=(deadline)
    self.deadline = Date.parse(deadline)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
  has_many :tasks, through: :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
    @tasks = current_user.tasks.where(deadline: Date.today).where(status: false).order("priority DESC")
    @project = Project.new
    @task = Task.new
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  def cancel
    respond_to do |format|
      format.js
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html {redirect_to projects_path, notice: 'Project was successfully created.'}
        format.json {render :show, status: :created, location: @project}
      else
        format.html {render :new}
        format.json {render json: @project.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html {redirect_to root_path, notice: 'Project was successfully updated.'}
        format.json {render :show, status: :ok, location: @project}
      else
        format.html {render :edit}
        format.json {render json: @project.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    false_tasks_status = @project.tasks.where(status: false)
    if false_tasks_status.empty?
      @project.tasks.map {|t| t.destroy}
      @project.destroy
      respond_to do |format|
        format.html {redirect_to projects_url, notice: 'Project was successfully destroyed.'}
        format.json {head :no_content}
      end
    else
      respond_to do |format|
        format.html {redirect_to projects_url, notice: 'Project cannot be destroyed.'}
        format.json {head :no_content}
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = current_user.projects.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :color)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_project, only: :search
  before_action :set_task, only: [:show, :edit, :update, :destroy, :complete]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    respond_to do |format|
      format.js
    end
  end

  # GET /tasks/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  def search
    @overdue_tasks = @project.tasks.where('deadline < ?', Date.today).where(status: false).order("priority DESC")
    @tasks = @project.tasks.where('deadline >= ?', Date.today).where(status: false).order("priority DESC")
    respond_to do |format|
      format.js {}
    end
  end

  def today
    @tasks = current_user.tasks.where(deadline: Date.today).where(status: false).order("priority DESC")
  end

  def next_seven_days
    @tasks = current_user.tasks.where('deadline > ?', Date.today).where('deadline <= ?', Date.today+7).where(status: false).order("priority DESC")
    respond_to do |format|
      format.js
    end
  end

  def completed
    @tasks = current_user.tasks.where(status: true)
    respond_to do |format|
      format.js
    end
  end

  def cancel
    respond_to do |format|
      format.js
    end
  end

  def complete
    binding.pry
    @task.update_attribute(:status, true)
    respond_to do |format|
      format.js
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html {redirect_to root_path, notice: 'Task was successfully created.'}
        format.json {render :show, status: :created, location: @task}
      else
        format.html {render :new}
        format.json {render json: @task.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html {redirect_to root_path, notice: 'Task was successfully updated.'}
        format.json {render :show, status: :ok, location: @task}
      else
        format.html {render :edit}
        format.json {render json: @task.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    binding.pry
    @task.destroy
    respond_to do |format|
      format.html {redirect_to root_path, notice: 'Task was successfully destroyed.'}
      format.json {head :no_content}
      format.js
    end
  end

  private
  def find_project
    @project = current_user.projects.find(params[:project_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:name, :priority, :deadline_format, :status, :project_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="navbar navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">TODO</a>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
          <li><%= link_to completed_tasks_path, remote: true, method: :get, class: 'layer2' do %>
                <i class="fa fa-ban"></i>
            <% end %>
          </li>
          <li><%= link_to 'Account', edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</header>


<%= yield %>


</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
    <div class="field" style="width: 200px; height: 35px; background-color: white; border: 1px solid grey;">
      <%= f.color_field :color, :value => '#ff0000', style: 'margin-top: 5px; border: none' %>
      <%= f.text_field :name, size: '17', style: 'border: none' %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit 'Add', class: 'btn btn-primary', style: 'width:100px;' %>
      <%= link_to 'Cancel', cancel_project_form_path, remote: true %>
    </div>
<% end %>

app/views/projects/_project.html.erb
<tr class="project_row">
  <td width="20px">
    <div class="circle" style="background:<%= project.color%>;"></div>
  </td>
  <td width="170px" class="project_name"><%= link_to project.name, search_path(project), remote: true %>
    <span class="low_grey project_count_<%= project.id %>"><%= project.tasks.where(status: false).count %></span></td>
  <td width="10px" id="ellipsis" class="hide">
    <i class="fa fa-ellipsis-v" aria-hidden="true">
      <ul class="menu hide">
        <li><%= link_to 'Edit', edit_project_path(project), remote: true %></li>
        <li><%= link_to 'Delete', project_path(project), method: :delete, class: "delete_task" %></li>
      </ul>
    </i>
  </td>
</tr>

app/views/projects/cancel.js.erb
$('#project_form').children().remove();
$("#add_project_form").show();

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/edit.js.erb
$('#project_form').children().remove();
$('<%= escape_javascript(render 'form' ) %>').appendTo('#project_form');
$("#add_project_form").hide();

app/views/projects/index.html.erb
<div class="left">
  <p id="notice"><%= notice %></p>

  <div style="margin-left:30%;">
    <h6><b><%= link_to 'Today', today_path, remote: true %></b>
      <span class="low_grey"><%= current_user.tasks.where(deadline: Date.today).count %></span>
    </h6>
    <h6><b><%= link_to 'Next 7 days', next_seven_days_path, remote: true %></b></h6>
    <br>
    <h6 style="text-decoration: underline;"><b>Projects</b></h6>
    <table>
      <tbody>
          <%= render @projects %>
      </tbody>
    </table>
    <div id="project_form">

    </div>
    <%= link_to '+ Add', new_project_path(@project), remote: true, style: "color:red !important", id: "add_project_form" %>
  </div>

</div>


<div class="center">
  <div style="margin-left: 20px; margin-right: 20px">
    <h4>Today <span class="low_grey"><%= Date.today.strftime("%a %d %b") %></span></h4>
    <table style="width: 100%">
      <tbody id='all_tasks'>
      <%= render @tasks %>
      </tbody>
    </table>

    <div id="task_form" style="width: 100%">
    </div>

    <%= link_to '+ Add', new_task_path(@task), remote: true, style: "color:red !important", id: "add_task_form" %>

  </div>

</div>


<div class="right">
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/new.js.erb
$('#project_form').children().remove();
$('<%= escape_javascript(render 'form' ) %>').appendTo('#project_form');
$("#add_project_form").hide();

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @project.color %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
    <div class="field">
      <%= f.text_field :name, size: '55', style: 'border: 1px solid grey; margin-top: 5px; padding: 5px; width: 70%;' %>
      <%= f.text_field :deadline_format, size: '10', style: 'border: 1px solid grey; margin-top: 5px;  padding: 5px 5px 5px 5px; width: 29%;' %>
    </div>
    <div style="width: 40%;margin-top: 5px; float: left;">
      <%= f.submit 'Add', class: 'btn btn-primary', style: 'width:100px;' %>
      <%= link_to 'Cancel', cancel_task_form_path, remote: true %>
    </div>
    <div class="field" style="width: 60%; float: left; margin-top: 5px; text-align: right;">
      <%= f.label :priority %>
      <%= f.select :priority, Task.priorities.keys %>
      <%= f.label :status %>
      <%= f.check_box :status %>
      <%= f.label :project_id %>
      <%= f.select :project_id, options_from_collection_for_select(Project.all, "id", "name") %>
    </div>
<% end %>

app/views/tasks/cancel.js.erb
$('#task_form').children().remove();
$("#add_task_form").show();

app/views/tasks/complete.js.erb
$('.complete_task').bind('ajax:success', function () {
  $(this).closest('.task_row').fadeOut()
});
$(".project_count_<%= @task.project.id %>").html("<%= @task.project.tasks.where(status: false).count%>");

app/views/tasks/completed.js.erb
$('#all_tasks').empty();
$('<%= escape_javascript(render @tasks ) %>').appendTo('#all_tasks');

app/views/tasks/delete.js.erb
$('.delete_task').bind('ajax:success', function () {
  $(this).closest('.task_row').fadeOut()
});

app/views/tasks/destroy.js.erb
$('.delete_task').bind('ajax:success', function () {
  $(this).closest('.task_row').fadeOut()
});
$(".project_count_<%= @task.project.id %>").html("<%= @task.project.tasks.count%>");

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$('#task_form').children().remove();
$('<%= escape_javascript(render 'form' ) %>').appendTo('#task_form');
$("#add_task_form").hide();

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Priority</th>
      <th>Deadline</th>
      <th>Status</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.priority %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status %></td>
        <td><%= task.project %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.js.erb
$('#task_form').children().remove();
$('<%= escape_javascript(render 'form' ) %>').appendTo('#task_form');
$("#add_task_form").hide();

app/views/tasks/next_seven_days.js.erb
$('#all_tasks').children().remove();
$('<%= escape_javascript(render @tasks ) %>').appendTo('#all_tasks');

$(".task_row").hover(
    function () {
      $(this).find("#ellipsis").removeClass("hide");
    },
    function () {
      $(this).find("#ellipsis").addClass("hide");
    }
);

$("td>.fa").hover(
    function () {
      $(this).find(".menu").removeClass("hide");
    },
    function () {
      $(this).find(".menu").addClass("hide");
    }
);

app/views/tasks/search.js.erb
$('#all_tasks').children().remove();
$('<%= escape_javascript(render @overdue_tasks) %>').appendTo('#all_tasks');
$('<%= escape_javascript(render @tasks) %>').appendTo('#all_tasks');

$(".task_row").hover(
    function () {
      $(this).find("#ellipsis").removeClass("hide");
    },
    function () {
      $(this).find("#ellipsis").addClass("hide");
    }
);

$("td>.fa").hover(
    function () {
      $(this).find(".menu").removeClass("hide");
    },
    function () {
      $(this).find(".menu").addClass("hide");
    }
);

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline_format %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project.id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/today.js.erb
$('#all_tasks').children().remove();
$('<%= escape_javascript(render @tasks ) %>').appendTo('#all_tasks');

$(".task_row").hover(
    function () {
      $(this).find("#ellipsis").removeClass("hide");
    },
    function () {
      $(this).find("#ellipsis").addClass("hide");
    }
);

$("td>.fa").hover(
    function () {
      $(this).find(".menu").removeClass("hide");
    },
    function () {
      $(this).find(".menu").addClass("hide");
    }
);